### PR TITLE
Add feature to suggest similar tasks when a task is not found

### PR DESCRIPTION
**Pull request by carl0smat3us**
Summary
---
This pull request implements one of the functionalities from issue #75, providing suggestions when a task is not found.

Details
---
Implemented a feature to suggest the most similar task if available when the user enters a task that does not exist.

Screenshots
---
Capture d’écran du 2024-05-26 00-20-04

### CODE REVIEW

**Comment by illBeRoy** [comment]
Hey @carl0smat3us. What a great idea! Thank you for taking the time to contribute to the project.

Can you please provide a couple of tests that demonstrate the feature? At the very least, we need two:
1. Test that shows the feature is working (run `task lim` and get a suggestion for `lint`)
2. Test that shows that, given no available suggestions, it doesn't show one (e.g. `task foo` should not show a suggestion if you only have a task named `lint`)

Once the tests pass our CI we can merge this.

**Comment by carl0smat3us** [comment]
> Hey @carl0smat3us. What a great idea! Thank you for taking the time to contribute to the project.
> 
> Can you please provide a couple of tests that demonstrate the feature? At the very least, we need two:
> 
> 1. Test that shows the feature is working (run `task lim` and get a suggestion for `lint`)
> 2. Test that shows that, given no available suggestions, it doesn't show one (e.g. `task foo` should not show a suggestion if you only have a task named `lint`)
> 
> Once the tests pass our CI we can merge this.

Thank you for reviewing my pull request.

I have added only one test because it is unnecessary to create another test for the scenario where there are no suggestions. For cases without suggestions, there is already a test called `test_exiting_with_code_127_and_printing_if_task_not_found` in the `TaskRunFailTestCase`. This existing test verifies that an error message is shown when a task is not found, without suggesting any alternatives tasks.

**Comment by illBeRoy** [comment]
That's a sharp observation @carl0smat3us, but the existing test only checks for the "could not find task X" substr:

```py
self.assertSubstr('could not find task "task_that_does_not_exist"', stdout)
```

We need to verify that it doesn't show any suggestion by explicitly asserting that `"did you mean"` is not a substr of the output.

We can implement that in the existing test, but IMO it should be its own test, so it's clear that we're specifically testing that no suggestion showed up.

Thanks!

**Comment by carl0smat3us** [comment]
> That's a sharp observation @carl0smat3us, but the existing test only checks for the "could not find task X" substr:
> 
> ```python
> self.assertSubstr('could not find task "task_that_does_not_exist"', stdout)
> ```
> 
> This assertion would pass even if we **do** show the suggestion, since "could not find..." would still be a substr of it.
> 
> We need to verify that it doesn't show any suggestion by explicitly asserting that `"did you mean"` is not a substr of the output.
> 
> We can implement that in the existing test, but IMO it should be its own test, so it's clear that we're specifically testing that no suggestion showed up.
> 
> Thanks!

I just added a test for this, can you review?

THANKS!

**Review by illBeRoy — APPROVED** [review]
Great job! Thanks for contributing to taskipy :)

**Comment by illBeRoy** [comment]
Just make sure to fix the tests and I'll re-review :)

**Review by illBeRoy — CHANGES_REQUESTED** [review]
Seems like CI is failing... Please fix the tests and I'll review again :)

**Comment by carl0smat3us** [comment]
> Seems like CI is failing... Please fix the tests \ lint and I'll review again :)

👍

**Review by illBeRoy — APPROVED** [review]
Looks good! Thank you for your contribution!

**Comment by illBeRoy** [comment]
Congrats, the feature made it into [v1.13.0](https://pypi.org/project/taskipy/1.13.0/)!

**Pull request merged**
