### PR TITLE
feature added -t option to measure task excution time (#61)

### PR DESCRIPTION
**Pull request by kkml4220**
## Summary

I have implemented a solution for issue #61 (ref: https://github.com/taskipy/taskipy/issues/61) which has been inactive for a while and also relevant to my own needs.

## Details

To prepare for future options using decorators, I have enhanced the runner by allowing it to receive a list of decorators. This enhancement supports an option to display the task name and measure the execution time with either `-t` or `--time`.

## Screenshots

image

### CODE REVIEW

**Comment by eugenetriguba** [comment]
@kkml4220 Hi Takahashi, thank you for taking the time to implement this! The changes make sense to me, but this change will need some tests for it in order for it to be accepted 🙂

**Comment by kkml4220** [comment]
@eugenetriguba Hi! Thank you for your review. I have added tests for the options and modules I implemented.

I also committed some minor fixes like inserting spaces, and it seems that these implementations are working well.

Regarding the test design, I extended the Taskipy options to be added as an array, anticipating that additional options might be added in the future. For unittest and E2E testing, I wrote a test to ensure that a task which should take 1 second actually has a measured execution time of approximately 0.9 to 1.1 seconds.

If these tests are insufficient, I would appreciate it if you could briefly suggest additional test cases or considerations.

I love using Taskipy and think it's a fantastic tool. Once again, thank you for your review.

**Comment by kkml4220** [comment]
Hi! @eugenetriguba When you have a moment, can you tell me if there is a problem with the design or if I should add more tests or if there is something wrong? If so, should I close this Pull Request and implement a new one? Any help, no matter how small, is welcome.

**Comment by illBeRoy** [comment]
Hey @kkml4220 ! Thanks for your contribution! I'll take over the review and keep you posted by EoW.

**Comment by illBeRoy** [comment]
Hey again @kkml4220 ! 
Thank you again for taking the time to open this PR. I know that you've already put a lot of effort into this PR, but I have a proposal that might interest you to expand the functionality of this PR beyond timing:

Today, we have an option to set a `runner` (see in [ADVANCED_DOCS](https://github.com/taskipy/taskipy/blob/master/docs/ADVANCED_FEATURES.md#custom-runners)).

So, technically, you can get the running time by setting:

```toml
[tool.taskipy.settings]
runner = "time"
```

Right now, you need to set the runner via the config file. 

My proposal:

Let's introduce a new argument, `-r, --runner`, that lets you set the runner for this specific execution.

You'll end up with the following command for timing:

```sh
task --r time lint_mypy
```

But this time around you'll be able to run it with other runners for other use cases, like a debugger process or even ssh.

What do you think? If you're up to the task I'll close this PR and open a feature request for that.

Cheers!

**Comment by illBeRoy** [comment]
hey! just a friendly ping :)
are you still interested in working on this feature?

**Comment by kkml4220** [comment]
Hi!, @illBeRoy. Firstly, I apologize for the delayed response. I've been quite busy with work and my graduate studies.

After carefully considering your proposal, I must admit that it hasn't sparked much interest for me. Specifically, using the Linux `time` command to achieve these tasks and accurately measuring the exact time, including overhead, for task execution doesn't particularly appeal to me.

I'm sorry that I can't fully support this feature.

I hope you understand. Best regards,

**Comment by illBeRoy** [comment]
Thank you for your quick and insightful reply.

Just a sidenote: I believe that the `--runner time` feature should yield more accurate timings, since using python to time the command includes the time it takes the CPU to spawn the subprocess, while the `--runner time` approach runs the `time` command inside the subprocess, therefore timing only the command itself.

One way or another, I'm sorry that you won't be contributing this feature, but hope to collaborate with you in the future!

**Pull request closed without merging**
